[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[functions."sync-results"]
  schedule = "*/2 * * * *"

[context.production.environment]
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL"
